### ISSUE TITLE
Compatibility with Virulent purple poison-giving liquid in the mod Undergarden

### ISSUE THREAD

**Issue by betterworld-sjq** [Terrails/colorful-hearts#11]
When I get poisonous by the virulent liquid in the mod, the hearts show all themselves instead of layers in one row.

**Comment by Terrails** [comment]
I'll look into this. I see where the issue lies but backporting all new features from 1.20.2 would take some time as I have basically kind of dropped support for any version below that unless there was some critical bug as 1.20.2 changed a bunch of things related to rendering. Might be better to wait for 1.20.2 version of the mod and then add the compatibility layer.

**Comment by V972** [comment]
I would really really appreciate if you consider backporting Undergarden support to 1.18, please, as I'm making a modpack with UG and was considering adding your mod.

**Comment by Terrails** [comment]
Compatibility is present on all 1.20 versions now. I am considering doing a backport to 1.19 but that is still only a consideration, so no promises for now. Unfortunately I do not plan going all the way back to 1.18 as its really old.
