### ISSUE TITLE
Mod causes part of the ui to act like it's in a lower resolution.

### ISSUE THREAD

**Issue by James-Fire** [Terrails/colorful-hearts#15]
![2023-12-29_19 51 57](https://github.com/Terrails/colorful-hearts/assets/41241412/144a8100-b7eb-4978-8275-7b906616b6d8)
![2023-12-29_19 53 26](https://github.com/Terrails/colorful-hearts/assets/41241412/6b930c7e-56d0-4aa3-b090-7400498433cc)

Resolution is 4k, Minecraft is in windowed mode.

The inventory and pause screen from vanilla are constrained to the smaller resolution denoted by the Armour, Hunger, and XP bars.

The inventory screen from Traveler's Backpack is similarly constrained.

This is my modlist, exported from the Curseforge Launcher.
[1.20.1.zip](https://github.com/Terrails/colorful-hearts/files/13796926/1.20.1.zip)

AFAICT, everything works fine.

Minecraft is 1.20.1, Forge is 47.2.0

**Comment by Terrails** [comment]
There was a similar issue before [#8 ](https://github.com/Terrails/colorful-hearts/issues/8#issuecomment-1752161497).

**Comment by vindocel** [comment]
I had the same problem, and I did an isolated test to find the problem, and I came to the conclusion that this problem is caused when trying to use the "Scaling Health" mod + Colorful Hearts, removing one or the other the problem is solved, so I believe that a compatibility layer will have to be added to be able to support both together, after all they both affect the rendering of hearts, but for now it's up to you to choose to play with one or the other

***
configurations used in the test if you want to replicate
Colorful Hearts 4.0.4
Scaling Health 8.0.1
Silent Lib 8.0.0
Minecraft is 1.20.1, neoforge is 47.1.88
***
@James-Fire

**Comment by Terrails** [comment]
The only thing I could do is to disable rendering when scaling health is present, but that defeats the purpose of the mod. Besides that I could only add a warning when loading the game to disable scaling health's config option to use colorful hearts and nothing else.

**Comment by vindocel** [comment]
Honestly, I don't see a reason to add a warning or anything, after all, the two mods are very similar so there's no reason to use both, just use one or the other, I think the best way would be to just put a warning in CurseForge and in Modrinth that the Scaling Health mod is incompatible`.
***
![Captura de tela 2024-01-20 152137](https://github.com/Terrails/colorful-hearts/assets/18473368/1437d7cd-52cc-4372-814a-0bde7650d721)
***
same as you added supported mod add unsupported mode
@Terrails
