### ISSUE TITLE
Suggestion: Display your health in numbers above the hearts 

### ISSUE THREAD

**Issue by KiraKayn** [Terrails/colorful-hearts#27]
I think this would be very useful, heres an idea of how it would look
![image](https://github.com/Terrails/colorful-hearts/assets/145915364/e35b9907-e65e-45d5-a450-a0401d4ee7f7)
The image is from another modpack, but should be pretty self explanatory. Btw thanks for this awesome mod ;D

**Comment by Terrails** [comment]
I have no intention of adding extra features like that, so that is a no. If you want something similar you could use the mod "overflowing bars" since it adds a number next to the hearts which represents the amount of heart layers you have. The mod is compatible with this one in case you want to use both.
