### ISSUE TITLE
[1.21-Neo] Crash when booting modpack. (fine on its own. possible mod conflict?)

### ISSUE THREAD

**Issue by Gbergz** [Terrails/colorful-hearts#37]
### Versions:
NeoForge: 21.0.97
Colorful Hearts: 10.1.3

### Crash report
https://gist.githubusercontent.com/Gbergz/4fe03aa64d40e88bea8dd8ae76f05d29/raw/bc817b09d363c0572504c8dd53f61b44b66914b0/gistfile1.txt

`"Cannot invoke "java.util.List.stream()" because "colors" is null"`

### Logs: (error at line 988)
https://gist.githubusercontent.com/Gbergz/e249753d3a1e1bf9e9aeb715e23b6418/raw/126b5bb5adb069fad31f67be1804b099cce9e196/gistfile1.txt

**Comment by Terrails** [comment]
This is an odd one. At first I thought it may be due to the config not loading on time, but the logs indicate that it loaded before the exception.
> [Colorful Hearts/]: Loading colorfulhearts.toml config file

Nevertheless, I will try to move the config call to a bit later in the code and it may behave then, as I am really unsure what the exact issue is. Through a bit of debugging it also seems like the config loading and texture atlas generation occur almost at the same time, so there may be some odd race condition when more mods are present.

**Comment by Terrails** [comment]
It seems like there's no easy way to move these calls. I have turned to the NeoForge discord for help and it seems like the config loading has been moved to an earlier stage from 21.0.98, so please do try to update NeoForge and see if the issue reoccurs.
>  `21.0.98` Load client and common configs earlier (now immediately after registries) (#1285)

**Comment by Gbergz** [comment]
I would try .98, but for now in my modpack I can't go above .97 due to breaking neo changes. Waiting for mods to update.

**Comment by Gbergz** [comment]
Works now! On latest NeoForge (v21.0.139).
