### ISSUE TITLE
Gui messed up

### ISSUE THREAD

**Issue by drmorgmd** [Terrails/colorful-hearts#8]
In survival mode and adventure mode (the two with hearts) the gui is shifted to a second smaller window like a pip. This dose not happen with the 4.0.1 and i believe it is related to line 78  MinecraftForge.EVENT_BUS.post(new RenderGuiOverlayEvent.Post(event.getWindow(), event.getGuiGraphics(), event.getPartialTick(), event.getOverlay()));

GUI overlay will be in top left corner however the mouse positions will be in the correct spots.

**Comment by Terrails** [comment]
I need more info as I see no issues on the same version using Forge.  
The specific line adds functionality to render extra overlays from other mods, this was specifically done to enable the overlay that Farmer's Delight shows with its comfort effect. If there is a compatibility issue I should be able to fix it if I knew which mod causes this issue.

**Comment by drmorgmd** [comment]
Ok, so using the 10/4/23 release 4.0.2 for MC 1.20.1 causes this issue, but downgrading to the 9/21/23 4.0.1 release fixes it. Issue persist with forge 47.2.0 47.1.47 and also neoforge 47.1.54. As far as what mod if any causes I'm not sure as we are up to 350ish mods in the pack and I wish I could narrow it down, I can say that we have farmer's delight and a bunch of add-ons to it as well as appleskin (seen other issue) the helth bar stays where it is supposed to be, and the hunger moves the chat and XP bar when not in any menu. Once you go into either inventory or escape, the whole screen is in the smaller window. This error also keep generating in log file "Error rendering overlay 'minecraft:player_health' java.lang.NullPointerException" 
![2023-10-07_19 45 29](https://github.com/Terrails/colorful-hearts/assets/31267097/89941c9f-8a32-4b66-8704-7cb3700ff62d)
![2023-10-07_19 45 56](https://github.com/Terrails/colorful-hearts/assets/31267097/03d5b22d-958b-4fe5-b554-255049bd3d76)
![2023-10-07_19 44 42](https://github.com/Terrails/colorful-hearts/assets/31267097/811c165c-9924-43c7-b596-154472c89d2a)

**Comment by Terrails** [comment]
Since this happens with the call to `RenderGuiOverlayEvent.Post`, you should try to remove Colorful Hearts altogether and see if the issue still occurs as it should unless another mod is preventing `RenderGuiOverlayEvent.Post` from being called.  
I would be slightly perplexed if it occurs only with Colorful Hearts, as Forge does the same call by itself in order to signal to mods to render any overlays. The only recommendation I can give you in that case is to start removing half of the mods each time (and back if no issue is found) until you can find the mod that actually causes this incompatibility.

**Comment by Terrails** [comment]
Also, if you could send the whole part of the log where that error is printed would be great just to see if there's anything of significance there.

**Comment by drmorgmd** [comment]
So removing the mod the issue is still there, but it's only with the 4.02 release this is the log file for the game when the GUI is messed up. 
[2023-10-08-2.log.gz](https://github.com/Terrails/colorful-hearts/files/12841663/2023-10-08-2.log.gz)

**Comment by Terrails** [comment]
If it happens without colorful hearts, I sadly cannot help you as the latest update to the mod just added back a call to a function that was always called when this mod was not present. You will unfortunately have to solve this on your own using the same recommendation I told you above and then report that to the developers of the mod (or mods) that cause this issue.

**Comment by drmorgmd** [comment]
Sorry I meant to say removing the mod the issue goes away, it is only there with the 4.0.2 version of the mod

**Comment by Terrails** [comment]
I have found the issue and it is related to scaling health mod. Both mods draw colored hearts and something bad is happening due to that. If you would like to still use colorful hearts together with scaling health, you should go into `scalinghealth-client.toml` config and toggle the `hearts.health.icons.style` to `VANILLA` in order to leave the heart rendering up to colorful hearts.

**Comment by drmorgmd** [comment]
awesome thank you
